from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(867, 495)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 75))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 192))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setTabletTracking(False)
        self.lineEdit.setToolTip("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_eq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eq.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_eq.setFont(font)
        self.pushButton_eq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_eq.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.verticalLayout.addWidget(self.pushButton_eq)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout.addWidget(self.pushButton_clear)
        self.pushButton_f = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_f.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_f.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_f.setObjectName("pushButton_f")
        self.verticalLayout.addWidget(self.pushButton_f)
        self.pushButton_f_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_f_ok.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_f_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_f_ok.setObjectName("pushButton_f_ok")
        self.verticalLayout.addWidget(self.pushButton_f_ok)
        self.pushButton_help_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_help_ok.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_help_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_help_ok.setObjectName("pushButton_help_ok")
        self.verticalLayout.addWidget(self.pushButton_help_ok)
        self.pushButton_help = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_help.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_help.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.pushButton_help.setObjectName("pushButton_help")
        self.verticalLayout.addWidget(self.pushButton_help)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_treg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_treg.setEnabled(True)
        self.pushButton_treg.setMinimumSize(QtCore.QSize(135, 46))
        self.pushButton_treg.setMaximumSize(QtCore.QSize(135, 46))
        self.pushButton_treg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_treg.setObjectName("pushButton_treg")
        self.horizontalLayout_4.addWidget(self.pushButton_treg)
        self.pushButton_un_treg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_un_treg.setMinimumSize(QtCore.QSize(25, 92))
        self.pushButton_un_treg.setMaximumSize(QtCore.QSize(25, 92))
        self.pushButton_un_treg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_un_treg.setObjectName("pushButton_un_treg")
        self.horizontalLayout_4.addWidget(self.pushButton_un_treg)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_sin = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sin.sizePolicy().hasHeightForWidth())
        self.pushButton_sin.setSizePolicy(sizePolicy)
        self.pushButton_sin.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_sin.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_sin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sin.setObjectName("pushButton_sin")
        self.horizontalLayout_3.addWidget(self.pushButton_sin)
        self.pushButton_cos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cos.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_cos.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_cos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cos.setObjectName("pushButton_cos")
        self.horizontalLayout_3.addWidget(self.pushButton_cos)
        self.pushButton_tan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tan.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_tan.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_tan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_tan.setObjectName("pushButton_tan")
        self.horizontalLayout_3.addWidget(self.pushButton_tan)
        self.pushButton_cot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cot.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_cot.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_cot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cot.setObjectName("pushButton_cot")
        self.horizontalLayout_3.addWidget(self.pushButton_cot)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_arsin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arsin.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_arsin.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_arsin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_arsin.setObjectName("pushButton_arsin")
        self.horizontalLayout_2.addWidget(self.pushButton_arsin)
        self.pushButton_arcos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arcos.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_arcos.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_arcos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_arcos.setObjectName("pushButton_arcos")
        self.horizontalLayout_2.addWidget(self.pushButton_arcos)
        self.pushButton_artan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_artan.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_artan.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_artan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_artan.setObjectName("pushButton_artan")
        self.horizontalLayout_2.addWidget(self.pushButton_artan)
        self.pushButton_arcot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arcot.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_arcot.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_arcot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_arcot.setObjectName("pushButton_arcot")
        self.horizontalLayout_2.addWidget(self.pushButton_arcot)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_gip = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_gip.setMinimumSize(QtCore.QSize(135, 46))
        self.pushButton_gip.setMaximumSize(QtCore.QSize(135, 46))
        self.pushButton_gip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_gip.setObjectName("pushButton_gip")
        self.horizontalLayout_5.addWidget(self.pushButton_gip)
        self.pushButton_un_gip = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_un_gip.setMinimumSize(QtCore.QSize(25, 92))
        self.pushButton_un_gip.setMaximumSize(QtCore.QSize(25, 92))
        self.pushButton_un_gip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_un_gip.setObjectName("pushButton_un_gip")
        self.horizontalLayout_5.addWidget(self.pushButton_un_gip)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_sh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sh.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_sh.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_sh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sh.setObjectName("pushButton_sh")
        self.horizontalLayout_6.addWidget(self.pushButton_sh)
        self.pushButton_ch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ch.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_ch.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_ch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_ch.setObjectName("pushButton_ch")
        self.horizontalLayout_6.addWidget(self.pushButton_ch)
        self.pushButton_th = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_th.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_th.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_th.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_th.setObjectName("pushButton_th")
        self.horizontalLayout_6.addWidget(self.pushButton_th)
        self.pushButton_cth = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cth.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_cth.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_cth.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cth.setObjectName("pushButton_cth")
        self.horizontalLayout_6.addWidget(self.pushButton_cth)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_arsh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arsh.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_arsh.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_arsh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_arsh.setObjectName("pushButton_arsh")
        self.horizontalLayout_7.addWidget(self.pushButton_arsh)
        self.pushButton_arch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arch.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_arch.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_arch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_arch.setObjectName("pushButton_arch")
        self.horizontalLayout_7.addWidget(self.pushButton_arch)
        self.pushButton_arth = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arth.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_arth.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_arth.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_arth.setObjectName("pushButton_arth")
        self.horizontalLayout_7.addWidget(self.pushButton_arth)
        self.pushButton_arcth = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arcth.setMinimumSize(QtCore.QSize(68, 46))
        self.pushButton_arcth.setMaximumSize(QtCore.QSize(68, 46))
        self.pushButton_arcth.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_arcth.setObjectName("pushButton_arcth")
        self.horizontalLayout_7.addWidget(self.pushButton_arcth)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_div = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_div.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_div.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_div.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout.addWidget(self.pushButton_div, 0, 0, 1, 1)
        self.pushButton_abs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_abs.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_abs.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_abs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_abs.setObjectName("pushButton_abs")
        self.gridLayout.addWidget(self.pushButton_abs, 1, 0, 1, 1)
        self.pushButton_root = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_root.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_root.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_root.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_root.setObjectName("pushButton_root")
        self.gridLayout.addWidget(self.pushButton_root, 1, 1, 1, 1)
        self.pushButton_degree = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_degree.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_degree.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_degree.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_degree.setObjectName("pushButton_degree")
        self.gridLayout.addWidget(self.pushButton_degree, 0, 2, 1, 1)
        self.pushButton_square = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_square.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_square.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_square.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_square.setObjectName("pushButton_square")
        self.gridLayout.addWidget(self.pushButton_square, 0, 1, 1, 1)
        self.pushButton_n_root = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n_root.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_n_root.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_n_root.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n_root.setObjectName("pushButton_n_root")
        self.gridLayout.addWidget(self.pushButton_n_root, 1, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(2, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_log.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_log.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_log.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_log.setObjectName("pushButton_log")
        self.horizontalLayout_9.addWidget(self.pushButton_log)
        self.pushButton_ln = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ln.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_ln.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_ln.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_ln.setObjectName("pushButton_ln")
        self.horizontalLayout_9.addWidget(self.pushButton_ln)
        self.pushButton_x = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_x.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_x.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_x.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_x.setObjectName("pushButton_x")
        self.horizontalLayout_9.addWidget(self.pushButton_x)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_const = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_const.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_const.setMaximumSize(QtCore.QSize(150, 50))
        self.pushButton_const.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_const.setObjectName("pushButton_const")
        self.horizontalLayout_8.addWidget(self.pushButton_const)
        self.pushButton_pi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pi.setMinimumSize(QtCore.QSize(38, 50))
        self.pushButton_pi.setMaximumSize(QtCore.QSize(38, 50))
        self.pushButton_pi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pi.setObjectName("pushButton_pi")
        self.horizontalLayout_8.addWidget(self.pushButton_pi)
        self.pushButton_e = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_e.setMinimumSize(QtCore.QSize(37, 50))
        self.pushButton_e.setMaximumSize(QtCore.QSize(37, 50))
        self.pushButton_e.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_e.setObjectName("pushButton_e")
        self.horizontalLayout_8.addWidget(self.pushButton_e)
        self.pushButton_c = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_c.setMinimumSize(QtCore.QSize(37, 50))
        self.pushButton_c.setMaximumSize(QtCore.QSize(37, 50))
        self.pushButton_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_c.setObjectName("pushButton_c")
        self.horizontalLayout_8.addWidget(self.pushButton_c)
        self.pushButton_i = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_i.setMinimumSize(QtCore.QSize(38, 50))
        self.pushButton_i.setMaximumSize(QtCore.QSize(38, 50))
        self.pushButton_i.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_i.setObjectName("pushButton_i")
        self.horizontalLayout_8.addWidget(self.pushButton_i)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_derivative = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_derivative.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_derivative.setMaximumSize(QtCore.QSize(150, 50))
        self.pushButton_derivative.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_derivative.setObjectName("pushButton_derivative")
        self.horizontalLayout_11.addWidget(self.pushButton_derivative)
        self.pushButton_integrate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_integrate.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_integrate.setMaximumSize(QtCore.QSize(150, 50))
        self.pushButton_integrate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_integrate.setObjectName("pushButton_integrate")
        self.horizontalLayout_11.addWidget(self.pushButton_integrate)
        self.pushButton_value = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_value.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_value.setMaximumSize(QtCore.QSize(150, 50))
        self.pushButton_value.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_value.setObjectName("pushButton_value")
        self.horizontalLayout_11.addWidget(self.pushButton_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.listHelp = QtWidgets.QListWidget(self.centralwidget)
        self.listHelp.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.listHelp.setFont(font)
        self.listHelp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listHelp.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.listHelp.setObjectName("listHelp")
        self.verticalLayout_2.addWidget(self.listHelp)
        self.listSolution = QtWidgets.QListWidget(self.centralwidget)
        self.listSolution.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(20)
        self.listSolution.setFont(font)
        self.listSolution.setObjectName("listSolution")
        self.verticalLayout_2.addWidget(self.listSolution)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Engineering Calculator"))
        self.centralwidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_eq.setText(_translate("MainWindow", "="))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))
        self.pushButton_f.setText(_translate("MainWindow", "f"))
        self.pushButton_f_ok.setText(_translate("MainWindow", "←"))
        self.pushButton_help_ok.setText(_translate("MainWindow", "✓"))
        self.pushButton_help.setText(_translate("MainWindow", "?"))
        self.pushButton_treg.setText(_translate("MainWindow", "Тригонометрические\nфункции"))
        self.pushButton_un_treg.setText(_translate("MainWindow", "←"))
        self.pushButton_sin.setText(_translate("MainWindow", "sin(f)"))
        self.pushButton_cos.setText(_translate("MainWindow", "cos(f)"))
        self.pushButton_tan.setText(_translate("MainWindow", "tan(f)"))
        self.pushButton_cot.setText(_translate("MainWindow", "cot(f)"))
        self.pushButton_arsin.setText(_translate("MainWindow", "arsin(f)"))
        self.pushButton_arcos.setText(_translate("MainWindow", "arcos(f)"))
        self.pushButton_artan.setText(_translate("MainWindow", "artan(f)"))
        self.pushButton_arcot.setText(_translate("MainWindow", "arcot(f)"))
        self.pushButton_gip.setText(_translate("MainWindow", "Гиперболические\nфункции"))
        self.pushButton_un_gip.setText(_translate("MainWindow", "←"))
        self.pushButton_sh.setText(_translate("MainWindow", "sh(f)"))
        self.pushButton_ch.setText(_translate("MainWindow", "ch(f)"))
        self.pushButton_th.setText(_translate("MainWindow", "th(f)"))
        self.pushButton_cth.setText(_translate("MainWindow", "cth(f)"))
        self.pushButton_arsh.setText(_translate("MainWindow", "arsh(f)"))
        self.pushButton_arch.setText(_translate("MainWindow", "arch(f)"))
        self.pushButton_arth.setText(_translate("MainWindow", "arth(f)"))
        self.pushButton_arcth.setText(_translate("MainWindow", "arcth(f)"))
        self.pushButton_div.setText(_translate("MainWindow", "f/g"))
        self.pushButton_abs.setText(_translate("MainWindow", "|f|"))
        self.pushButton_root.setText(_translate("MainWindow", "√f"))
        self.pushButton_degree.setText(_translate("MainWindow", "f^g"))
        self.pushButton_square.setText(_translate("MainWindow", "f^2"))
        self.pushButton_n_root.setText(_translate("MainWindow", "∛f"))
        self.pushButton_log.setText(_translate("MainWindow", "log(f,g)"))
        self.pushButton_ln.setText(_translate("MainWindow", "ln(f)"))
        self.pushButton_x.setText(_translate("MainWindow", "x"))
        self.pushButton_const.setText(_translate("MainWindow", "Константы"))
        self.pushButton_pi.setText(_translate("MainWindow", "π"))
        self.pushButton_e.setText(_translate("MainWindow", "e"))
        self.pushButton_c.setText(_translate("MainWindow", "c"))
        self.pushButton_i.setText(_translate("MainWindow", "i"))
        self.pushButton_derivative.setText(_translate("MainWindow", "derivative"))
        self.pushButton_integrate.setText(_translate("MainWindow", "integrate"))
        self.pushButton_value.setText(_translate("MainWindow", "value"))
